apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
  namespace: dev
spec:   
  selector: 
    app: nginx-pod
  type: NodePort
  ports:
    - port: 80
      nodePort: 30002 #指定绑定的node的端口号， 默认范围是30000-32767，如果不指定则在此区间随机分配
      targetPort: 80 #pod端口