
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
  creationTimestamp: "2023-06-22T15:01:04Z"
  generation: 1
  labels:
    app: kube-prometheus-stack-coredns
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 46.8.0
    chart: kube-prometheus-stack-46.8.0
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-coredns
  namespace: prometheus
  resourceVersion: "640798412"
  uid: 606e76f8-86cb-4679-a29d-915dae2bf3cc
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: kube-prometheus-stack-coredns
      release: prometheus
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-05T15:17:34Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeDNS
  name: kube-dns
  namespace: kube-system
  resourceVersion: "665137284"
  uid: 8c0222cb-8ee3-11ea-a2e3-42010a9c0086
spec:
  clusterIP: 10.16.69.10
  clusterIPs:
  - 10.16.69.10
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: dmetrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
  creationTimestamp: "2023-06-22T15:01:03Z"
  labels:
    app: kube-prometheus-stack-coredns
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 46.8.0
    chart: kube-prometheus-stack-46.8.0
    heritage: Helm
    jobLabel: coredns
    release: prometheus
  name: prometheus-kube-prometheus-coredns
  namespace: kube-system
  resourceVersion: "640798267"
  uid: f891caf5-dc42-4924-bde2-0b4eba3a29cf
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}



# curl -H "content-type:application/json" -d '
# {
#   "loginOrEmail": "admin"
# }' 
# http://localhost:8080/api/user/password/reset


# kube-system   kube-dns                                             10.64.209.2:53,10.64.210.2:53,10.64.209.2:53 + 1 more...            3y97d
# kube-system   prometheus-kube-prometheus-coredns                   10.64.209.2:9153,10.64.210.2:9153                                   49d

