apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes: ["ReadWriteMany"]
  # storageClassName: nfs
  resources:
    requests:
      storage: 9Mi
  selector:
    matchLabels:
      pv: test1
