apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-tomcat-http
  namespace: dev
  # annotations: 
  #   kubernets.io/ingress.class: "nginx" 
  #还可以是     kubernetes.io/ingress.class: prod-pri-ingress tke上的
  #    kubernetes.io/ingress.class: nginx-in aliyun上的
  #作用等同于  ingressClassName: ingress-pri ctyun上的
spec:
  # ingressClassName: nginx
  rules:
  - host: tomcat.myaaa.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: tomcat-svc
            port:
              number: 8080