apiVersion: cloud.tencent.com/v1alpha1
kind: NginxIngress
metadata:
  creationTimestamp: "2022-10-25T03:00:29Z"
  generation: 1
  managedFields:
  - apiVersion: cloud.tencent.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:ingressClass: {}
        f:service:
          .: {}
          f:annotation:
            .: {}
            f:service.kubernetes.io/service.extensiveParameters: {}
          f:type: {}
        f:workLoad:
          .: {}
          f:hpa:
            .: {}
            f:enable: {}
            f:maxReplicas: {}
            f:metrics: {}
            f:minReplicas: {}
          f:template:
            .: {}
            f:affinity: {}
            f:container:
              .: {}
              f:image: {}
              f:resources:
                .: {}
                f:limits:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
                f:requests:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
          f:type: {}
    manager: TC_Http
    operation: Update
    time: "2022-10-25T03:00:29Z"
  name: prod-pub-ingress
  resourceVersion: "11654695149"
  selfLink: /apis/cloud.tencent.com/v1alpha1/nginxingresses/prod-pub-ingress
  uid: b0fd6b6e-6686-4fe3-9924-90e8fdb52ea4
spec:
  ingressClass: prod-pub-ingress
  service:
    annotation:
      service.kubernetes.io/service.extensiveParameters: '{"InternetAccessible":{"InternetChargeType":"TRAFFIC_POSTPAID_BY_HOUR","InternetMaxBandwidthOut":2048}}'
    type: LoadBalancer
  workLoad:
    hpa:
      enable: true
      maxReplicas: 2
      metrics:
      - pods:
          metricName: k8s_pod_rate_cpu_core_used_limit
          targetAverageValue: "80"
        type: Pods
      minReplicas: 1
    template:
      affinity: {}
      container:
        image: ccr.ccs.tencentyun.com/paas/nginx-ingress-controller:v1.1.3
        resources:
          limits:
            cpu: "0.5"
            memory: 1024Mi
          requests:
            cpu: "0.25"
            memory: 256Mi
    type: deployment
